language: java

git:
  depth: false

env:
  global:
#    - MAVEN_OPTS="-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
    - secure: "V1+7pbeeI3RU86O+y7nsHB78w7SmCOlCMr8/O1hsEn9OywwyAxFCXU5/0q2dewsOBCOKyLOnnC24Etx3MDBUq7f6iw5zXwXbfx9HZ5Tj+mMYeS4z+AYdrPB73OScFo83AdZF/kNd+CA3+Vu0hSv/yXHGW+7G74OrWcx4OtTsKcFdSbk8/IyVae2Q+GuNJetvIWp9sz+mBZh1oHvHmGCug5B0qPwTMEBwial1IalwN4xB4mZFnulIB7qEYpo47cXjcFNXN3unPBTAzBFrTD/bK9UJRJn1XByUgpkfjGU06Kp6qZYl9sllGV9mYuYdj4VbeLx0osy4XVnjqn8Dt8rL0G8GZQf2C3VPNzTikgLjh4RaPQH4+DhPbZlMGF8mEyjVUgu51iLjGGLkdD8YljrB9gPUJuo3dCjLWdp3mN44nw5Sr7BJ5nBjy2/Hy2zJibRzG305exZ0uynq6Tl4MAgRKmj4TODCJnta1HaElApBNmdRAIPjHMq4QDskPyUpaPXG/PCrOXHlOtf68aLngQ90ZVHjrXZL3GOF6tsQk/noZWDNUZQ3ZmeuoCy+4y2h+WmUesNLfOhoThbFWvi/iUsNvUMLHyJlL+hKH3iYIW8W6aX2Y+HH4Aqa41k7lzfvZBLtwEqDXDRMywsZAlNC9NrX/pgqm4Nt/pSo4zYsfx3xrfM="
    - secure: "huqdNK62/ncK/lhlAFmkDgSCcAWL8IT3QYyaIw54WvQ35cYCht1qBK0HLqwYNqwhq4t2PSSggH7UQoiiD64nOlb/HQ+pB63NAL6Quq8p+3jsgoQBG7ejg7Bz5kIXWMxGx7OHJYHrcYJKVsh5J3hG1yjy487c7sg56WzXoWzsSioZXp5/DwsJcMtJjtDkNF4gp5DZp+j9ggMvXhY9cqwHcXKws6VGO3pN6Vkg8SYf2vHImhr/R9V7xLgKmvMxgb6K0aKP4XGZ/LbGzE6T2UvZBnZhKy5c2T5fSvDwwqV54UJkS26dWVlwus7rBRFSc4rXFMdzS+IU9NDOPn698Gc5BOXnCG+Gar5jg36MG54F9SWqUwhydQj1jCXNTiDbteLliDWSbGXZB+xBJlI2qP/47ZejmqXPfW1329i4b2RZlAd8CrAEGvysyHWJqT1RCqf8F3mv+9M9fyaj5PVEw0sbbQ8UBR1XZSzhRfOV2nYMcXzd3yP2AR7YMV/027YzW5CfVjsyle+KlVN8rNol8+OMctcYH32FyYI+nDUuEpJ7T3XefOMEY4IkZHFOW3/KL9mOjT0dMKgIphxU9gEZQJPSFaVFB0hym2j7yAwPZrbuh1eFkRhCT0fkiGA6sMR6h9dagoNyQGDWWuxT8qdZcSMxiS/1hEgQOVPopziJ8jcDo5E="
    - secure: "LcBYmfL7Ak8Yh8Gfar8uX4OlraSpWmCmu+e3O0ZqQ7uuHDM0e1SwI7x0rrzEJJgmTyyly3hWjVE6rH/EEzo7moWL0u+aE6cgn8nPBRT56lIGZCIIN+EPiMLDkPQD5PZqBASwxwxFap+YK9ijbvyK8Q389K83/snMZpXHsZvkFHZ6RrJvv4v2Jgm6mPvq7N1pWKjMgbGqQg4QkJD92/k/6O2H0euABONKm/IR3/69VfuyIRMFHkUxMN3Y5v+dUCJ085Ba6YwobMb03gYX64NoMGZ7mP4NryrFmydF+79h8MSkQyjporxqej4Ib+nsRM5XNejAHHLSdVCBLvf9pnoPOHW5nsS7z4hZ2nMixaGeBheyODcE4Q0XA8StGS/VGynwhvfuAvrifDztHUYy5kSjHdQdGLauh67AmkbuQKi8UDaufiQGQpVjLX6OdL0m4eer6Ybi0zPIKuPFEQMzFk5d5Wm+BUrPcGCp3g2XcBQYdW9lbE+3TKiDfLJRFG5gcmP7IeAT7M7tUDcsToiCCan1PPohMbd1TAvNPECKdjyzaN0PfKNFd1nO0bZ3a4PjknXdmonSk03Q8aP5CDDhkalwjavRcxs9B79GMNhfSqL8G8rJNWZbcpOGeqG03ZJSuf2uGvIl+8eoGb52DlNbrzkNNHoDC5NNQKnQHZkA6DZceT8="
    - secure: "ULDh14+tt6dSgVXFRxrLNGdS46Np+dmGjaVdBrLClMWrir+3RieiXYEN0u25xWSHMom6pgROT3uw15+TZb7IfveeHaflDrww/1Cuikde0SFco7eHGBL+OgispDTncWQgGWqM3wb6Iwn6koeXutl4Enn0u21RcaVthDn1h79KDPhpI24OyqyYZ5P+8zJ0MUe4IvfuvbtocFhxEvSJXOLR4y0CHakF3+MqdP8rFXUde05kxQ++XcvyyvbY+gKPZoI+sWn0CLtsGW3gIKucfhdC4btU5VFF3SdkzYGQ8i4BvgyAJwdhvTVbNVin/lY9o36iG3KlzQlzSbG67FwmGWYRHJHHliRQNvDPzAAEZarvoA9fvYZ8ERMEqXaRZVl/smzeOmJHYBIzVyACFRxSRK55QO6IKDGrysOGzsjiHNFWXYTDgnLvLQRrFKi3DQ4grz0A/uIpdwHci5nTnyoJ+rsVbeXwv1IQNkEPcCjEp52l5OwAJ7oAkb4S6rGlS3Eeop2/MINL4d8COz3P5HBaGG4btxgnCWxGmSaSXBYcregfJ1pi4Yans8UgUb2gD/966+IVGUR+u4yUXwV4cyEJo44iUNIwo8MGHxKS+AEUUc8VpdazUxhxcBx5OKSS9oKy3EAwOy77xrWyQAVhZnelYKEn1BlwuRaKzrz64X4m40CzpFw="
    - secure: "Auf8QuEupXTJIvNIhe+nrlzgMTkNrcwU8X4VRBaDYlEvxhZ0USBQvcYfBBRigoyJXdGhF+Ny+NGtzXy40Q33oaa9+pa1Ju/H5Iy9m4PGnX3n/Qug3vSuzt/jXqYIOGROec7/3EZ5iWVyQ7EbbtPHT894uLx2mWv9Mb1BEhVIs4D/SV+KsMbOwPCRkRCMPISXxx4ue/bpeiMA5Pz/9p13ixeNImIZ9Nn52i0krhGpQdhGV73cAmHiPhoHLHOSRej7pQe1JTSppGzVCYOQysBBZTk5kA/avPBrKciMNa+JjFLXR8B8/LM9JtsRSEVU0963u4zx/0DzFS985OTt1TY9iZKMvlOPeos+9Cnxk378gmYcHAQRdOra0/zuDXlkQ5xj/Ar9Os4M9Zd9wn8lXFBDsNDeLtqZfq0vkJynvdoBt5Ah38tM/ytzdj4d4RbB62Lia1Qd7cnpWNEjShm2pMFRCwfkMTxxaE4Iac8sZMnOggaNLeXoFjJC1p/cnsXRYR1N5uqIjd78ON5ZT8J8WFjflRf2g5EpN3I8rW9rOJrcHpU+qTVc2scL5Z5QVCVDyhwwtcWOIIfXmBx/gjvgF4Pasy6ugH8VZp5SejdSG5ySfDimz9VkYMpKvYagj4brsV741Sqofacb8unlrs4kUC2mgX8AK5RcLH3MQChfmP5t6AE="

jobs:
  include:
    - os: linux
      dist: bionic
      jdk: openjdk8
      services:
        - xvfb
    - os: osx
      osx_image: xcode9.3

#jdk:
#  - openjdk8

# ----- Enable caching of downloaded artifacts -----
# Gradle’s dependency management mechanism resolves declared modules and their corresponding artifacts from a binary
# repository. Once downloaded, the files will be re-used from the cache. You need to tell Travis CI explicitly that you
# want to store and use the Gradle cache and Wrapper for successive invocations of the build.

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# -----

#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/libexec/java_home -V; fi

install: skip #true

before_script:
  - chmod +x gradlew

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo $DISPLAY; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew build -PjvmTarget=1.8 -PsourceCompatibility=1.8 -Djava.awt.headless=false --stacktrace; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./gradlew build -PjvmTarget=1.8 -PsourceCompatibility=1.8 --stacktrace; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mvn -B clean package -Djava.awt.headless=false; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mvn -B clean package; fi

# deploy on success, but only if we are on master
after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LATEST_VERSION="$(curl -Ls https://api.bintray.com/packages/codacy/Binaries/codacy-coverage-reporter/versions/_latest | jq -r .name)"; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -Ls -o codacy-coverage-reporter "https://dl.bintray.com/codacy/Binaries/${LATEST_VERSION}/codacy-coverage-reporter-linux"; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x codacy-coverage-reporter; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./codacy-coverage-reporter report -l Kotlin -r build/reports/jacoco/test/jacocoTestReport.xml; fi
    - bash <(curl -s https://codecov.io/bash) -c -F unittests

